#!/bin/bash

# nvm?
if hash nvm 2>/dev/null; then
  nvm use
fi

echo "Node version should be > 0.10.x"
node --version

echo "Ruby version should be > 1.8.7"
ruby --version
gem --version

echo "Sass version should be > 3.3.x"
sass --version

# gulp
npm install --global gulp

# dependencies
npm install
